server:
  port: ${SERVER_PORT:-2333}
  address: 0.0.0.0
lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
    sources:
      youtube: false
      http: true
    playerUpdateInterval: 5
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5_SIMPLY
      - WEB
spring:
  main:
    banner-mode: off
